using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace OpenApiClientGenerator;

internal sealed class OpenApiClientEmitter
{
    private readonly OpenApiDocumentModel _document;
    private readonly string _clientNamespace;
    private readonly string _clientName;
    private readonly Dictionary<string, string> _objectTypeNames;

    public OpenApiClientEmitter(OpenApiDocumentModel document, string clientNamespace, string clientName)
    {
        _document = document;
        _clientNamespace = clientNamespace;
        _clientName = SanitizeIdentifier(clientName, pascalCase: true);
        _objectTypeNames = BuildObjectTypeNames();
    }

    public string Emit()
    {
        var writer = new CodeWriter();
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Globalization;");
        writer.WriteLine("using System.Net.Http;");
        writer.WriteLine("using System.Net.Http.Headers;");
        writer.WriteLine("using System.Net.Http.Json;");
        writer.WriteLine("using System.Text;");
        writer.WriteLine("using System.Text.Json;");
        writer.WriteLine("using System.Text.Json.Serialization;");
        writer.WriteLine("using System.Threading;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine();
        writer.WriteLine("namespace " + _clientNamespace);
        writer.WriteLine("{");
        writer.Indent();

        EmitClient(writer);
        EmitModels(writer);

        writer.Unindent();
        writer.WriteLine("}");

        return writer.ToString();
    }

    private void EmitClient(CodeWriter writer)
    {
        writer.WriteLine("public sealed partial class " + _clientName);
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("private static readonly JsonSerializerOptions DefaultSerializerOptions = CreateDefaultSerializerOptions();");
        writer.WriteLine("private readonly HttpClient _httpClient;");
        writer.WriteLine("private readonly JsonSerializerOptions _serializerOptions;");
        writer.WriteLine();
        writer.WriteLine("public " + _clientName + "(HttpClient httpClient, JsonSerializerOptions? serializerOptions = null)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("_httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));");
        writer.WriteLine("_serializerOptions = serializerOptions ?? DefaultSerializerOptions;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();

        EmitOperations(writer);
        EmitHelpers(writer);

        writer.Unindent();
        writer.WriteLine("}");
    }

    private void EmitOperations(CodeWriter writer)
    {
        foreach (var pathEntry in _document.Paths.OrderBy(static item => item.Key, StringComparer.Ordinal))
        {
            foreach (var operationEntry in pathEntry.Value.Operations
                         .OrderBy(static item => GetHttpMethodRank(item.Key))
                         .ThenBy(static item => item.Key, StringComparer.Ordinal))
            {
                EmitOperation(writer, pathEntry.Key, operationEntry.Key, pathEntry.Value, operationEntry.Value);
                writer.WriteLine();
            }
        }
    }

    private void EmitOperation(
        CodeWriter writer,
        string path,
        string httpMethod,
        OpenApiPathModel pathModel,
        OpenApiOperationModel operation)
    {
        var methodName = BuildMethodName(path, httpMethod, operation.OperationId);
        var parameters = GetParameters(pathModel, operation);
        var reservedNames = new HashSet<string>(parameters.Select(static parameter => parameter.VariableName), StringComparer.Ordinal);
        var requestBody = GetRequestBody(operation, reservedNames);
        var response = GetPrimaryResponse(operation);
        var returnType = response.IsVoid ? "Task" : "Task<" + response.TypeName + ">";

        var signatureParameters = new List<string>();
        foreach (var parameter in parameters)
        {
            signatureParameters.Add(parameter.TypeName + " " + parameter.VariableName + (parameter.Required ? string.Empty : " = null"));
        }

        if (requestBody is not null)
        {
            signatureParameters.Add(requestBody.TypeName + " " + requestBody.ParameterName + (requestBody.Required ? string.Empty : " = null"));
        }

        signatureParameters.Add("CancellationToken cancellationToken = default");

        writer.WriteLine("public async " + returnType + " " + methodName + "Async(" + string.Join(", ", signatureParameters) + ")");
        writer.WriteLine("{");
        writer.Indent();

        writer.WriteLine("var pathBuilder = $\"" + BuildPathExpression(path, parameters.Where(static parameter => parameter.Kind == ParameterKind.Path).ToList()) + "\";");
        writer.WriteLine("var queryParameters = new List<string>();");

        foreach (var parameter in parameters.Where(static parameter => parameter.Kind == ParameterKind.Query))
        {
            EmitQueryParameter(writer, parameter);
        }

        writer.WriteLine("if (queryParameters.Count > 0)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("pathBuilder = pathBuilder + \"?\" + string.Join(\"&\", queryParameters);");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();

        writer.WriteLine("using var request = new HttpRequestMessage(HttpMethod." + ToHttpMethodProperty(httpMethod) + ", pathBuilder);");

        foreach (var parameter in parameters.Where(static parameter => parameter.Kind == ParameterKind.Header))
        {
            EmitHeaderParameter(writer, parameter);
        }

        if (requestBody is not null)
        {
            EmitRequestBody(writer, requestBody);
        }

        writer.WriteLine();
        writer.WriteLine("using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);");
        writer.WriteLine("response.EnsureSuccessStatusCode();");

        if (!response.IsVoid)
        {
            EmitResponseHandling(writer, response);
        }

        writer.Unindent();
        writer.WriteLine("}");
    }

    private void EmitQueryParameter(CodeWriter writer, MethodParameter parameter)
    {
        if (parameter.IsCollection)
        {
            if (parameter.Required)
            {
                writer.WriteLine("foreach (var item in " + parameter.VariableName + ")");
                writer.WriteLine("{");
                writer.Indent();
                writer.WriteLine("AddQueryParameter(queryParameters, \"" + parameter.OriginalName + "\", item);");
                writer.Unindent();
                writer.WriteLine("}");
            }
            else
            {
                writer.WriteLine("if (" + parameter.VariableName + " is not null)");
                writer.WriteLine("{");
                writer.Indent();
                writer.WriteLine("foreach (var item in " + parameter.VariableName + ")");
                writer.WriteLine("{");
                writer.Indent();
                writer.WriteLine("AddQueryParameter(queryParameters, \"" + parameter.OriginalName + "\", item);");
                writer.Unindent();
                writer.WriteLine("}");
                writer.Unindent();
                writer.WriteLine("}");
            }
        }
        else
        {
            if (parameter.Required)
            {
                writer.WriteLine("AddQueryParameter(queryParameters, \"" + parameter.OriginalName + "\", " + parameter.VariableName + ");");
            }
            else
            {
                writer.WriteLine("if (" + parameter.VariableName + " is not null)");
                writer.WriteLine("{");
                writer.Indent();
                writer.WriteLine("AddQueryParameter(queryParameters, \"" + parameter.OriginalName + "\", " + parameter.VariableName + ");");
                writer.Unindent();
                writer.WriteLine("}");
            }
        }
    }

    private void EmitHeaderParameter(CodeWriter writer, MethodParameter parameter)
    {
        if (parameter.Required)
        {
            writer.WriteLine("request.Headers.TryAddWithoutValidation(\"" + parameter.OriginalName + "\", FormatUriValue(" + parameter.VariableName + "));");
            return;
        }

        writer.WriteLine("if (" + parameter.VariableName + " is not null)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("request.Headers.TryAddWithoutValidation(\"" + parameter.OriginalName + "\", FormatUriValue(" + parameter.VariableName + "));");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private void EmitRequestBody(CodeWriter writer, RequestBodyDescriptor requestBody)
    {
        var shouldGuard = !requestBody.Required;
        if (shouldGuard)
        {
            writer.WriteLine("if (" + requestBody.ParameterName + " is not null)");
            writer.WriteLine("{");
            writer.Indent();
        }

        switch (requestBody.MediaKind)
        {
            case MediaKind.Json:
                writer.WriteLine("request.Content = JsonContent.Create(" + requestBody.ParameterName + ", options: _serializerOptions);");
                break;
            case MediaKind.Text:
                writer.WriteLine("request.Content = new StringContent(" + requestBody.ParameterName + ", Encoding.UTF8, \"" + requestBody.MediaType + "\");");
                break;
            case MediaKind.Binary:
                writer.WriteLine("request.Content = new ByteArrayContent(" + requestBody.ParameterName + ");");
                writer.WriteLine("request.Content.Headers.ContentType = new MediaTypeHeaderValue(\"" + requestBody.MediaType + "\");");
                break;
            default:
                writer.WriteLine("request.Content = new StringContent(JsonSerializer.Serialize(" + requestBody.ParameterName + ", _serializerOptions), Encoding.UTF8, \"" + requestBody.MediaType + "\");");
                break;
        }

        if (shouldGuard)
        {
            writer.Unindent();
            writer.WriteLine("}");
        }
    }

    private void EmitResponseHandling(CodeWriter writer, ResponseDescriptor response)
    {
        switch (response.MediaKind)
        {
            case MediaKind.Json:
                writer.WriteLine("if (response.Content.Headers.ContentLength == 0)");
                writer.WriteLine("{");
                writer.Indent();
                writer.WriteLine("return default;");
                writer.Unindent();
                writer.WriteLine("}");
                writer.WriteLine();
                writer.WriteLine("return await response.Content.ReadFromJsonAsync<" + response.DeserializeTypeName + ">(_serializerOptions, cancellationToken).ConfigureAwait(false);");
                break;
            case MediaKind.Text:
                writer.WriteLine("return await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);");
                break;
            case MediaKind.Binary:
                writer.WriteLine("return await response.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);");
                break;
            default:
                writer.WriteLine("return await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);");
                break;
        }
    }

    private void EmitHelpers(CodeWriter writer)
    {
        writer.WriteLine("private static JsonSerializerOptions CreateDefaultSerializerOptions()");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("var options = new JsonSerializerOptions");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("PropertyNameCaseInsensitive = true,");
        writer.Unindent();
        writer.WriteLine("};");
        writer.WriteLine("options.Converters.Add(new JsonStringEnumConverter());");
        writer.WriteLine("return options;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("private static void AddQueryParameter<T>(List<string> queryParameters, string name, T value)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("queryParameters.Add(Uri.EscapeDataString(name) + \"=\" + Uri.EscapeDataString(FormatUriValue(value)));");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("private static string FormatUriValue<T>(T value)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (value is null)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("return string.Empty;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("return value switch");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("string text => text,");
        writer.WriteLine("DateTimeOffset dateTimeOffset => dateTimeOffset.ToString(\"O\", CultureInfo.InvariantCulture),");
        writer.WriteLine("DateTime dateTime => dateTime.ToString(\"O\", CultureInfo.InvariantCulture),");
        writer.WriteLine("bool boolean => boolean ? \"true\" : \"false\",");
        writer.WriteLine("byte[] buffer => Convert.ToBase64String(buffer),");
        writer.WriteLine("IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),");
        writer.WriteLine("_ => value.ToString() ?? string.Empty,");
        writer.Unindent();
        writer.WriteLine("};");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private void EmitModels(CodeWriter writer)
    {
        foreach (var schemaEntry in _document.Schemas.OrderBy(static item => item.Key, StringComparer.Ordinal))
        {
            if (!_objectTypeNames.TryGetValue(schemaEntry.Key, out var typeName))
            {
                continue;
            }

            writer.WriteLine();
            writer.WriteLine("public sealed partial class " + typeName);
            writer.WriteLine("{");
            writer.Indent();

            var properties = GetObjectProperties(schemaEntry.Value);
            if (properties.Count == 0)
            {
                writer.WriteLine("public Dictionary<string, JsonElement>? AdditionalData { get; set; }");
            }
            else
            {
                foreach (var property in properties.OrderBy(static item => item.JsonName, StringComparer.Ordinal))
                {
                    writer.WriteLine("[JsonPropertyName(\"" + property.JsonName + "\")]");
                    var initializer = property.Required && IsReferenceType(property.TypeName) ? " = default!;" : string.Empty;
                    writer.WriteLine("public " + property.TypeName + " " + property.PropertyName + " { get; set; }" + initializer);
                    writer.WriteLine();
                }

                writer.TrimTrailingBlankLine();
            }

            writer.Unindent();
            writer.WriteLine("}");
        }
    }

    private Dictionary<string, string> BuildObjectTypeNames()
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var schemaEntry in _document.Schemas)
        {
            if (IsObjectSchema(schemaEntry.Value))
            {
                result[schemaEntry.Key] = SanitizeIdentifier(schemaEntry.Key, pascalCase: true);
            }
        }

        return result;
    }

    private bool IsObjectSchema(OpenApiSchemaModel schema)
    {
        var resolved = _document.ResolveSchema(schema);
        if (resolved.OneOf.Count > 0 || resolved.AnyOf.Count > 0)
        {
            return false;
        }

        if (resolved.AdditionalProperties is not null && resolved.Properties.Count == 0 && resolved.AllOf.Count == 0)
        {
            return false;
        }

        if (string.Equals(resolved.Type, "object", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (resolved.Properties.Count > 0)
        {
            return true;
        }

        return resolved.AllOf.Any(IsObjectSchema);
    }

    private List<PropertyDescriptor> GetObjectProperties(OpenApiSchemaModel schema)
    {
        var resolved = _document.ResolveSchema(schema);
        var properties = new Dictionary<string, PropertyDescriptor>(StringComparer.Ordinal);
        CollectProperties(resolved, properties, new HashSet<OpenApiSchemaModel>());
        return properties.Values.ToList();
    }

    private void CollectProperties(
        OpenApiSchemaModel schema,
        Dictionary<string, PropertyDescriptor> properties,
        HashSet<OpenApiSchemaModel> visited)
    {
        var resolved = _document.ResolveSchema(schema);
        if (!visited.Add(resolved))
        {
            return;
        }

        foreach (var part in resolved.AllOf)
        {
            CollectProperties(part, properties, visited);
        }

        foreach (var propertyEntry in resolved.Properties)
        {
            var required = resolved.RequiredProperties.Contains(propertyEntry.Key);
            properties[propertyEntry.Key] = new PropertyDescriptor(
                propertyEntry.Key,
                SanitizeIdentifier(propertyEntry.Key, pascalCase: true),
                ResolveSchemaType(propertyEntry.Value, required, SchemaUsage.Property),
                required);
        }
    }

    private List<MethodParameter> GetParameters(OpenApiPathModel pathModel, OpenApiOperationModel operation)
    {
        var map = new Dictionary<string, MethodParameter>(StringComparer.OrdinalIgnoreCase);

        foreach (var parameter in pathModel.Parameters.Concat(operation.Parameters))
        {
            var resolved = _document.ResolveParameter(parameter);
            var location = resolved.Location.ToLowerInvariant();

            if (location != "path" && location != "query" && location != "header")
            {
                continue;
            }

            var kind = location switch
            {
                "path" => ParameterKind.Path,
                "query" => ParameterKind.Query,
                _ => ParameterKind.Header,
            };

            var typeName = ResolveSchemaType(resolved.Schema, resolved.Required || kind == ParameterKind.Path, SchemaUsage.Parameter);
            var variableName = SanitizeIdentifier(resolved.Name, pascalCase: false);
            var isCollection = IsCollectionType(typeName);
            var key = location + ":" + resolved.Name;

            map[key] = new MethodParameter(resolved.Name, variableName, typeName, kind, resolved.Required || kind == ParameterKind.Path, isCollection);
        }

        return map.Values
            .OrderBy(static parameter => (int)parameter.Kind)
            .ThenBy(static parameter => parameter.OriginalName, StringComparer.Ordinal)
            .ToList();
    }

    private RequestBodyDescriptor? GetRequestBody(OpenApiOperationModel operation, HashSet<string> reservedNames)
    {
        if (operation.RequestBody is null)
        {
            return null;
        }

        var requestBody = _document.ResolveRequestBody(operation.RequestBody);
        if (requestBody.Content.Count == 0)
        {
            return null;
        }

        var content = SelectMediaType(requestBody.Content);
        var parameterName = "body";
        if (reservedNames.Contains(parameterName))
        {
            parameterName = "requestBody";
        }

        return new RequestBodyDescriptor(
            parameterName,
            ResolveSchemaType(content.MediaType.Schema, requestBody.Required, SchemaUsage.RequestBody),
            requestBody.Required,
            ClassifyMediaType(content.MediaTypeName),
            content.MediaTypeName);
    }

    private ResponseDescriptor GetPrimaryResponse(OpenApiOperationModel operation)
    {
        var candidate = operation.Responses
            .Where(static entry => entry.Key.StartsWith("2", StringComparison.Ordinal) || string.Equals(entry.Key, "default", StringComparison.OrdinalIgnoreCase))
            .OrderBy(static entry => GetResponseRank(entry.Key))
            .FirstOrDefault();

        if (string.IsNullOrWhiteSpace(candidate.Key))
        {
            return ResponseDescriptor.Void();
        }

        var response = _document.ResolveResponse(candidate.Value);
        if (response.Content.Count == 0)
        {
            return ResponseDescriptor.Void();
        }

        var content = SelectMediaType(response.Content);
        if (content.MediaType.Schema is null)
        {
            return ResponseDescriptor.Void();
        }

        var typeName = ResolveSchemaType(content.MediaType.Schema, required: false, usage: SchemaUsage.Response);
        return new ResponseDescriptor(typeName, RemoveNullableSuffix(typeName), ClassifyMediaType(content.MediaTypeName));
    }

    private SelectedMediaType SelectMediaType(Dictionary<string, OpenApiMediaTypeModel> content)
    {
        var ordered = content
            .OrderByDescending(static entry => GetMediaTypePriority(entry.Key))
            .ThenBy(static entry => entry.Key, StringComparer.OrdinalIgnoreCase)
            .First();

        return new SelectedMediaType(ordered.Key, ordered.Value);
    }

    private string BuildMethodName(string path, string httpMethod, string? operationId)
    {
        if (!string.IsNullOrWhiteSpace(operationId))
        {
            return SanitizeIdentifier(operationId!, pascalCase: true);
        }

        var builder = new StringBuilder();
        builder.Append(SanitizeIdentifier(httpMethod, pascalCase: true));

        foreach (var segment in path.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries))
        {
            if (segment.StartsWith("{", StringComparison.Ordinal) && segment.EndsWith("}", StringComparison.Ordinal))
            {
                builder.Append("By");
                builder.Append(SanitizeIdentifier(segment.Trim('{', '}'), pascalCase: true));
            }
            else
            {
                builder.Append(SanitizeIdentifier(segment, pascalCase: true));
            }
        }

        return builder.ToString();
    }

    private string BuildPathExpression(string path, List<MethodParameter> pathParameters)
    {
        var result = path;
        foreach (var parameter in pathParameters)
        {
            result = result.Replace(
                "{" + parameter.OriginalName + "}",
                "{" + "Uri.EscapeDataString(FormatUriValue(" + parameter.VariableName + "))" + "}");
        }

        return result;
    }

    private string ResolveSchemaType(OpenApiSchemaModel? schema, bool required, SchemaUsage usage)
    {
        if (schema is null)
        {
            return ApplyNullability("string", required);
        }

        var effectiveRequired = required && !schema.Nullable;
        if (schema.Reference is not null)
        {
            var componentName = _document.GetSchemaComponentName(schema.Reference);
            if (_objectTypeNames.TryGetValue(componentName, out var objectTypeName))
            {
                return ApplyNullability(objectTypeName, effectiveRequired);
            }

            return ResolveSchemaType(_document.ResolveSchemaReference(schema.Reference), effectiveRequired, usage);
        }

        if (schema.OneOf.Count > 0 || schema.AnyOf.Count > 0)
        {
            return ApplyNullability("JsonElement", effectiveRequired);
        }

        var type = schema.Type?.ToLowerInvariant();
        switch (type)
        {
            case "string":
                return ApplyNullability(ResolveStringType(schema.Format), effectiveRequired);
            case "integer":
                return ApplyNullability(schema.Format == "int64" ? "long" : "int", effectiveRequired);
            case "number":
                if (schema.Format == "float")
                {
                    return ApplyNullability("float", effectiveRequired);
                }

                return ApplyNullability(schema.Format == "double" ? "double" : "decimal", effectiveRequired);
            case "boolean":
                return ApplyNullability("bool", effectiveRequired);
            case "array":
                var itemType = RemoveNullableSuffix(ResolveSchemaType(schema.Items, required: true, usage: usage));
                var collectionType = usage == SchemaUsage.Parameter
                    ? "IEnumerable<" + itemType + ">"
                    : "List<" + itemType + ">";
                return ApplyNullability(collectionType, effectiveRequired);
            case "object":
                if (schema.AdditionalProperties is not null && schema.Properties.Count == 0 && schema.AllOf.Count == 0)
                {
                    var valueType = RemoveNullableSuffix(ResolveSchemaType(schema.AdditionalProperties, required: true, usage: SchemaUsage.Property));
                    return ApplyNullability("Dictionary<string, " + valueType + ">", effectiveRequired);
                }

                return ApplyNullability("JsonElement", effectiveRequired);
        }

        if (schema.Properties.Count > 0 || schema.AllOf.Count > 0)
        {
            return ApplyNullability("JsonElement", effectiveRequired);
        }

        return ApplyNullability("string", effectiveRequired);
    }

    private static string ResolveStringType(string? format)
    {
        return format switch
        {
            "date" => "DateTime",
            "date-time" => "DateTimeOffset",
            "uuid" => "Guid",
            "byte" => "byte[]",
            "binary" => "byte[]",
            _ => "string",
        };
    }

    private static string RemoveNullableSuffix(string typeName)
    {
        return typeName.EndsWith("?", StringComparison.Ordinal) ? typeName.Substring(0, typeName.Length - 1) : typeName;
    }

    private static string ApplyNullability(string typeName, bool required)
    {
        if (required || typeName.EndsWith("?", StringComparison.Ordinal))
        {
            return typeName;
        }

        return typeName + "?";
    }

    private static bool IsCollectionType(string typeName)
    {
        return typeName.Contains("IEnumerable<", StringComparison.Ordinal) || typeName.Contains("List<", StringComparison.Ordinal);
    }

    private static bool IsReferenceType(string typeName)
    {
        var nonNullable = RemoveNullableSuffix(typeName);
        return nonNullable switch
        {
            "bool" => false,
            "int" => false,
            "long" => false,
            "float" => false,
            "double" => false,
            "decimal" => false,
            "DateTime" => false,
            "DateTimeOffset" => false,
            "Guid" => false,
            "JsonElement" => false,
            _ => true,
        };
    }

    private static string SanitizeIdentifier(string value, bool pascalCase)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return pascalCase ? "Generated" : "generated";
        }

        var words = value
            .Split(new[] { '-', '_', '.', '/', ' ', '{', '}', '[', ']', ':', ';' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(static word => new string(word.Where(char.IsLetterOrDigit).ToArray()))
            .Where(static word => word.Length > 0)
            .ToList();

        if (words.Count == 0)
        {
            return pascalCase ? "Generated" : "generated";
        }

        var builder = new StringBuilder();
        for (var index = 0; index < words.Count; index++)
        {
            var word = words[index];
            if (index == 0 && !pascalCase)
            {
                builder.Append(char.ToLowerInvariant(word[0]));
                if (word.Length > 1)
                {
                    builder.Append(word.Substring(1));
                }

                continue;
            }

            builder.Append(char.ToUpperInvariant(word[0]));
            if (word.Length > 1)
            {
                builder.Append(word.Substring(1));
            }
        }

        if (builder.Length == 0)
        {
            builder.Append(pascalCase ? "Generated" : "generated");
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return EscapeKeyword(builder.ToString());
    }

    private static string EscapeKeyword(string identifier)
    {
        return identifier switch
        {
            "class" => "@class",
            "namespace" => "@namespace",
            "params" => "@params",
            "event" => "@event",
            "operator" => "@operator",
            "base" => "@base",
            "string" => "@string",
            "object" => "@object",
            "int" => "@int",
            "long" => "@long",
            "default" => "@default",
            "internal" => "@internal",
            "public" => "@public",
            "private" => "@private",
            "protected" => "@protected",
            "void" => "@void",
            "ref" => "@ref",
            _ => identifier,
        };
    }

    private static string ToHttpMethodProperty(string httpMethod)
    {
        return SanitizeIdentifier(httpMethod, pascalCase: true);
    }

    private static int GetHttpMethodRank(string httpMethod)
    {
        return httpMethod.ToLowerInvariant() switch
        {
            "get" => 0,
            "post" => 1,
            "put" => 2,
            "patch" => 3,
            "delete" => 4,
            "head" => 5,
            "options" => 6,
            "trace" => 7,
            _ => int.MaxValue,
        };
    }

    private static int GetResponseRank(string statusCode)
    {
        if (string.Equals(statusCode, "default", StringComparison.OrdinalIgnoreCase))
        {
            return int.MaxValue;
        }

        return int.TryParse(statusCode, NumberStyles.Integer, CultureInfo.InvariantCulture, out var parsed)
            ? parsed
            : int.MaxValue - 1;
    }

    private static int GetMediaTypePriority(string mediaType)
    {
        return ClassifyMediaType(mediaType) switch
        {
            MediaKind.Json => 3,
            MediaKind.Text => 2,
            MediaKind.Binary => 1,
            _ => 0,
        };
    }

    private static MediaKind ClassifyMediaType(string mediaType)
    {
        if (mediaType.IndexOf("json", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            return MediaKind.Json;
        }

        if (mediaType.StartsWith("text/", StringComparison.OrdinalIgnoreCase))
        {
            return MediaKind.Text;
        }

        if (mediaType.IndexOf("octet-stream", StringComparison.OrdinalIgnoreCase) >= 0)
        {
            return MediaKind.Binary;
        }

        return MediaKind.Other;
    }

    private enum ParameterKind
    {
        Path = 0,
        Query = 1,
        Header = 2,
    }

    private enum SchemaUsage
    {
        Parameter,
        RequestBody,
        Response,
        Property,
    }

    private enum MediaKind
    {
        Json,
        Text,
        Binary,
        Other,
    }

    private sealed class MethodParameter
    {
        public MethodParameter(string originalName, string variableName, string typeName, ParameterKind kind, bool required, bool isCollection)
        {
            OriginalName = originalName;
            VariableName = variableName;
            TypeName = typeName;
            Kind = kind;
            Required = required;
            IsCollection = isCollection;
        }

        public string OriginalName { get; }

        public string VariableName { get; }

        public string TypeName { get; }

        public ParameterKind Kind { get; }

        public bool Required { get; }

        public bool IsCollection { get; }
    }

    private sealed class RequestBodyDescriptor
    {
        public RequestBodyDescriptor(string parameterName, string typeName, bool required, MediaKind mediaKind, string mediaType)
        {
            ParameterName = parameterName;
            TypeName = typeName;
            Required = required;
            MediaKind = mediaKind;
            MediaType = mediaType;
        }

        public string ParameterName { get; }

        public string TypeName { get; }

        public bool Required { get; }

        public MediaKind MediaKind { get; }

        public string MediaType { get; }
    }

    private sealed class ResponseDescriptor
    {
        public ResponseDescriptor(string typeName, string deserializeTypeName, MediaKind mediaKind)
        {
            TypeName = typeName;
            DeserializeTypeName = deserializeTypeName;
            MediaKind = mediaKind;
        }

        public string TypeName { get; }

        public string DeserializeTypeName { get; }

        public MediaKind MediaKind { get; }

        public bool IsVoid => string.IsNullOrEmpty(TypeName);

        public static ResponseDescriptor Void()
        {
            return new ResponseDescriptor(string.Empty, string.Empty, MediaKind.Other);
        }
    }

    private sealed class PropertyDescriptor
    {
        public PropertyDescriptor(string jsonName, string propertyName, string typeName, bool required)
        {
            JsonName = jsonName;
            PropertyName = propertyName;
            TypeName = typeName;
            Required = required;
        }

        public string JsonName { get; }

        public string PropertyName { get; }

        public string TypeName { get; }

        public bool Required { get; }
    }

    private sealed class SelectedMediaType
    {
        public SelectedMediaType(string mediaTypeName, OpenApiMediaTypeModel mediaType)
        {
            MediaTypeName = mediaTypeName;
            MediaType = mediaType;
        }

        public string MediaTypeName { get; }

        public OpenApiMediaTypeModel MediaType { get; }
    }

    private sealed class CodeWriter
    {
        private readonly StringBuilder _builder = new StringBuilder();
        private int _indentLevel;

        public void Indent()
        {
            _indentLevel++;
        }

        public void Unindent()
        {
            _indentLevel--;
        }

        public void WriteLine(string value = "")
        {
            if (value.Length == 0)
            {
                _builder.AppendLine();
                return;
            }

            _builder.Append(new string(' ', _indentLevel * 4));
            _builder.AppendLine(value);
        }

        public void TrimTrailingBlankLine()
        {
            while (_builder.Length > 0 && (_builder[_builder.Length - 1] == '\r' || _builder[_builder.Length - 1] == '\n'))
            {
                _builder.Length--;
            }

            if (_builder.Length == 0)
            {
                return;
            }

            var lastLineFeed = -1;
            for (var index = _builder.Length - 1; index >= 0; index--)
            {
                if (_builder[index] == '\n')
                {
                    lastLineFeed = index;
                    break;
                }
            }

            if (lastLineFeed < 0)
            {
                return;
            }

            _builder.AppendLine();
        }

        public override string ToString()
        {
            return _builder.ToString();
        }
    }
}
